# File from https://github.com/localstack/localstack/blob/master/docker-compose.yml, with
# some modifications
services:
  localstack:
    # docker-compose.yml has 'container_name' property set for service 'localstack' but
    # this property is not supported by Testcontainers, consider removing it
    # container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: "localstack/localstack:3.7.0"
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES= s3,secretsmanager
      - PERSISTENCE=1
      - AWS_ACCESS_KEY_ID= "1234"
      - AWS_SECRET_ACCESS_KEY= "1234"
      - AWS_DEFAULT_REGION= "us-east-1"
      - AWS_REGION= "us-east-1"
      - SKIP_SSL_CERT_DOWNLOAD= 1

    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
